- name: variables from prompt
  hosts: local
  connection: local
  tasks:
  - name: print course info
    ansible.builtin.debug:
    msg: "Hello, Course name is: {{ COURSE }}, Duration is: {{ DURATION }}, trainer is: {{ TRAINER }}"