- name: gather facts
  hosts: local
  connection: local
  # Ansible collects the info of target server, befoe executes any other fact
  tasks:
  - name: facts
    ansible.builtin.debug:
      msg: "{{ ansible_facts }}"
