- name: install packages
  hosts: local
  connection: local
  tasks:
    - name: print message
      ansible.builtin.package:
        name: {{ item }}
      loop:
      - nginx
      - mysql
      - zip